# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Ho_Chi_Minh"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore prod"
      prefix-development: "chore dev"
      include: "scope"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "vue"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "vite*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "@vitejs/*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "*eslint*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "svgo"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "typescript"
      - dependency-name: "prettier"          
      - dependency-name: "*"
          - "version-update:semver-major"
