name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.yml'

env:
  PRIMARY_NODE_VERSION: 14

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --ignore-engines --frozen-lockfile

      - name: Lint code
        run: yarn lint

  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --ignore-engines --frozen-lockfile

      - name: Type check
        run: yarn type-check

  build:
    needs: [lint, type-check]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --ignore-engines --frozen-lockfile

      - name: Build
        run: yarn build

  print-information:
    if: ${{ github.ref }} == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: echo github information
        run: echo ${{ toJSON(github) }}
